# ============================================================================
#  INSECURE demo broker  --  Module MQTT, "before" state
#  Reproduces the vulnerable broker from mqtt_iot_telemetry.pcap.
#  DO NOT use this configuration anywhere but the lab.
# ============================================================================
listener 1883 0.0.0.0
allow_anonymous true          # <-- any client may connect with no credentials
persistence false
connection_messages true
log_type all
