#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""build_lab.py — generate the `lab` command runner's step files and manifests.

The Read/Do/Check curriculum gives every terminal step a short, stable token
(l0, l1, l1b, ...). This script walks content_levels.LEVELS and, for every 'cmd'
step, writes a runnable step file plus its expected-output check, and the two
manifests the `lab` runner consumes:

  lab/steps/<tok>        the command text (runnable with `sh`; the leading
                         '# gist' comment is kept — valid shell, and shown to
                         the student when the runner echoes the command)
  lab/steps/<tok>.check  the step's 'expect' text (skipped when a step has none)
  lab/commands.tsv       one line per token: <tok>\\t<level n>\\t<gist>   (for `lab list`)
  lab/aliases.sh         `alias <tok>='lab <tok>'` per token             (so typing `l1` works)

Tokens and the gist/command split come from content_levels.type_tokens / split_cmd,
so this stays the single source of truth. Paths are anchored to the repo root
computed from __file__, so it runs the same from anywhere.

Run:  python3 build/build_lab.py
"""
import os

from content_levels import LEVELS, type_tokens, split_cmd

# Repo root = parent of build/ (this file lives in build/).
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LAB = os.path.join(ROOT, "lab")
STEPS = os.path.join(LAB, "steps")


def build():
    os.makedirs(STEPS, exist_ok=True)

    rows = []       # (tok, level_n, label) for commands.tsv
    toks = []       # ordered token list for aliases.sh
    n_steps = n_checks = 0

    for lv in LEVELS:
        tokmap = type_tokens(lv)
        for i, st in enumerate(lv.get("steps", [])):
            if st.get("kind") != "cmd":
                continue
            tok = tokmap[i]
            gist, command = split_cmd(st["text"])

            # step file: the full text (comment + command) — comments are valid shell,
            # and keeping the '# gist' line means the runner shows it to the student.
            with open(os.path.join(STEPS, tok), "w") as f:
                f.write(st["text"].rstrip("\n") + "\n")
            n_steps += 1

            # check file: the expected output, when the step records one.
            exp = st.get("expect")
            if exp:
                with open(os.path.join(STEPS, tok + ".check"), "w") as f:
                    f.write(exp.rstrip("\n") + "\n")
                n_checks += 1

            # commands.tsv label: prefer the human gist; when a step has no leading
            # comment, fall back to its first command line so `lab list` is never blank.
            label = gist or (command.splitlines()[0].strip() if command.strip() else tok)
            # keep the TSV single-line + tab-clean.
            label = label.replace("\t", " ").replace("\n", " ")
            rows.append((tok, lv["n"], label))
            toks.append(tok)

    # commands.tsv
    with open(os.path.join(LAB, "commands.tsv"), "w") as f:
        for tok, n, label in rows:
            f.write("%s\t%d\t%s\n" % (tok, n, label))

    # aliases.sh — source this so typing `l1` runs `lab l1` (lab/ must be on PATH).
    with open(os.path.join(LAB, "aliases.sh"), "w") as f:
        f.write("# Auto-generated by build/build_lab.py — do not edit by hand.\n")
        f.write("# Source me (postcreate wires this into ~/.bashrc) so `l1`, `l1b`, ...\n")
        f.write("# each run the lab runner. Requires the lab/ dir on PATH.\n")
        for tok in toks:
            f.write("alias %s='lab %s'\n" % (tok, tok))

    print("build_lab: wrote %d step files, %d checks, %d tokens" % (n_steps, n_checks, len(toks)))
    print("  steps dir : %s" % STEPS)
    print("  manifests : %s , %s" % (os.path.join(LAB, "commands.tsv"),
                                     os.path.join(LAB, "aliases.sh")))
    print("  tokens    : %s" % " ".join(toks))
    return toks


if __name__ == "__main__":
    build()
